name: params
version: 2.0.0
description: A sample web application
homepage: https://github.com/DisDis/params
author: Igor Demyanov
environment:
  sdk: '>=1.14.0'
dependencies:
  code_transformers: '>=0.4.2 <0.4.3'
dependency_overrides:
dev_dependencies:
  transformer_test: any
  logging: any
  barback: any
  mockito: any
  test: '>=0.12.0'
transformers:
 - params
