name: params
version: 2.0.2
description: A sample web application
homepage: https://github.com/DisDis/params
author: Igor Demyanov<igor.demyanov@gmail.com>

environment:
  sdk: '>=1.14.0'
dependency_overrides:
dev_dependencies:
  transformer_test: any
  logging: any
  barback: any
  mockito: any
  test: '>=0.12.0'
transformers:
 - params
